# Generated by Django 4.0.6 on 2022-07-27 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_usuario_direccion'),
    ]

    operations = [
        migrations.CreateModel(
            name='ejercicios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_ejercicio', models.CharField(max_length=12)),
                ('descripcion', models.CharField(max_length=150)),
                ('do', models.CharField(max_length=12)),
            ],
        ),
    ]
