# Generated by Django 4.0.6 on 2022-07-27 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_ejercicios'),
    ]

    operations = [
        migrations.AddField(
            model_name='ejercicios',
            name='detalle',
            field=models.CharField(default='Detalle', max_length=150),
        ),
        migrations.AlterField(
            model_name='ejercicios',
            name='descripcion',
            field=models.CharField(default='Descripcion', max_length=150),
        ),
        migrations.AlterField(
            model_name='ejercicios',
            name='do',
            field=models.CharField(default='do', max_length=12),
        ),
    ]
