# Generated by Django 4.0.6 on 2022-07-27 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_ejercicios_detalle_alter_ejercicios_descripcion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ejercicios',
            name='estatus',
            field=models.CharField(default='1', max_length=1),
        ),
    ]
